'use client'

import { useState, useEffect, useRef } from 'react'
import { FileText, Copy, Check, Download, Lock } from 'lucide-react'
import type { ScriptLayer } from '@/lib/utils/result-transform'
import { useUserTier } from '@/hooks/useUserTier'

interface ScriptLayerCardProps {
  script:   ScriptLayer
  onCopy?:  () => void
}

// ── CapCut export formatter ───────────────────────────────────────────────────

function buildCapCutScript(script: ScriptLayer): string {
  const header = [
    '=== TTLike™ CapCut Script ===',
    `Duration: ${script.total_duration || '—'}`,
    `Scenes: ${script.lines.length}`,
    '',
    '──────────────────────────────',
    '',
  ].join('\n')

  const scenes = script.lines.map((line, i) =>
    [
      `SCENE ${i + 1}  |  ${line.time_range}  |  ${line.beat.toUpperCase()}`,
      ``,
      `🎤 SAY:    "${line.say}"`,
      `🎬 DO:     ${line.do}`,
      `💫 VIBE:   ${line.emotion}`,
      ``,
      '──────────────────────────────',
      '',
    ].join('\n')
  )

  const footer = [
    'PRODUCTION TIPS',
    '• Film each scene in one continuous take',
    '• Match your energy to the VIBE tag',
    '• Keep DO directions visible while filming',
    '',
    'Generated by TTLike.com',
  ].join('\n')

  return header + scenes.join('') + footer
}

function downloadTxt(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ── CapCut export button ──────────────────────────────────────────────────────

function CapCutExportButton({ script }: { script: ScriptLayer }) {
  const { tier } = useUserTier()
  const [downloaded, setDownloaded] = useState(false)
  const downloadedTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => () => { if (downloadedTimerRef.current) clearTimeout(downloadedTimerRef.current) }, [])

  if (tier.loading) {
    return <div className="h-8 w-28 bg-gray-100 rounded-lg animate-pulse" />
  }

  const canExport = tier.tier_name !== 'free'

  if (!canExport) {
    return (
      <div className="relative group">
        <button
          disabled
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-gray-400 bg-gray-50 border border-gray-200 cursor-not-allowed"
        >
          <Lock className="w-3.5 h-3.5" />
          CapCut Export
        </button>
        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-52 p-2.5 bg-gray-900 text-white text-xs rounded-lg opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-10 text-center">
          <p className="font-semibold mb-0.5">Creator Plan Required</p>
          <p className="text-gray-300 text-[11px]">Upgrade for CapCut-formatted script downloads.</p>
          <a
            href="/pricing"
            className="block mt-1.5 text-pink-400 font-bold hover:text-pink-300 pointer-events-auto"
            onClick={e => e.stopPropagation()}
          >
            View Plans →
          </a>
        </div>
      </div>
    )
  }

  function handleDownload() {
    const content  = buildCapCutScript(script)
    const filename = `ttlike-capcut-${Date.now()}.txt`
    downloadTxt(content, filename)
    setDownloaded(true)
    if (downloadedTimerRef.current) clearTimeout(downloadedTimerRef.current)
    downloadedTimerRef.current = setTimeout(() => setDownloaded(false), 3000)
  }

  return (
    <button
      onClick={handleDownload}
      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-violet-600 bg-violet-50 hover:bg-violet-100 border border-violet-200 transition-colors"
    >
      {downloaded
        ? <><Check className="w-3.5 h-3.5 text-green-500" />Downloaded!</>
        : <><Download className="w-3.5 h-3.5" />CapCut Export</>
      }
    </button>
  )
}

// ── Main card ─────────────────────────────────────────────────────────────────

export function ScriptLayerCard({ script, onCopy }: ScriptLayerCardProps) {
  const [copied, setCopied] = useState(false)
  const copiedTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => () => { if (copiedTimerRef.current) clearTimeout(copiedTimerRef.current) }, [])

  function buildPlainText() {
    return script.lines.map(l =>
      `[${l.time_range}] ${l.beat}\nSAY: ${l.say}\nDO: ${l.do}\nFEEL: ${l.emotion}`
    ).join('\n\n')
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(buildPlainText())
      setCopied(true)
      if (copiedTimerRef.current) clearTimeout(copiedTimerRef.current)
      copiedTimerRef.current = setTimeout(() => setCopied(false), 2000)
      onCopy?.()
    } catch {}
  }

  return (
    <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden">
      {/* Header — stacks to two rows on very narrow screens */}
      <div className="px-4 sm:px-6 py-3 sm:py-4 border-b border-gray-100">
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-indigo-600 shrink-0" />
            <h2 className="font-semibold text-gray-900">Script</h2>
            {script.total_duration && (
              <span className="text-xs text-gray-400 font-mono">{script.total_duration}</span>
            )}
          </div>
          {/* Copy all — icon + text on sm+, icon-only on mobile */}
          <button
            onClick={handleCopy}
            aria-label={copied ? 'Copied' : 'Copy script'}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium text-gray-600 hover:bg-gray-100 transition-colors shrink-0"
          >
            {copied
              ? <><Check className="w-3.5 h-3.5 text-green-500" /><span className="hidden sm:inline">Copied!</span></>
              : <><Copy className="w-3.5 h-3.5" /><span className="hidden sm:inline">Copy all</span></>
            }
          </button>
        </div>
        {/* CapCut export on its own row — avoids overflow on narrow phones */}
        <div className="mt-2">
          <CapCutExportButton script={script} />
        </div>
      </div>

      <div className="divide-y divide-gray-100">
        {script.lines.map((line, i) => (
          <div key={i} className="px-4 sm:px-6 py-4 hover:bg-gray-50 transition-colors">
            {/* Scene meta */}
            <div className="flex flex-wrap items-center gap-1.5 mb-3">
              <span className="text-xs font-mono text-gray-400">{line.time_range}</span>
              <span className="px-2 py-0.5 rounded-full bg-indigo-50 text-indigo-600 text-xs font-medium">
                {line.beat}
              </span>
              <span className="px-2 py-0.5 rounded-full bg-gray-100 text-gray-500 text-xs">
                {line.emotion}
              </span>
            </div>

            <div className="space-y-2.5">
              <div className="flex gap-2.5">
                <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-wider w-7 shrink-0 pt-1">SAY</span>
                <p className="text-sm text-gray-900 font-medium leading-relaxed">{line.say}</p>
              </div>
              <div className="flex gap-2.5">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider w-7 shrink-0 pt-1">DO</span>
                <p className="text-sm text-gray-500 leading-relaxed">{line.do}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
