import { redirect } from 'next/navigation'
import { Suspense } from 'react'
import { createClient } from '@/lib/supabase/server'
import { StudioClient } from './StudioClient'
import { SITE_URL } from '@/lib/constants'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title:       'Viral Studio — Generate a Shoot-Ready TikTok Script · TTLike',
  description: 'Paste any TikTok URL. Get a scene-by-scene script, hook breakdown, and pre-shoot checklist in ~20 seconds. Free to try.',
  alternates:  { canonical: `${SITE_URL}/studio` },
  openGraph: {
    title:       'Viral Studio — Shoot-Ready TikTok Scripts · TTLike',
    description: 'From TikTok URL to shoot-ready script in 20 seconds. Hook + body + CTA + checklist — generated by AI.',
    url:         `${SITE_URL}/studio`,
  },
}

// Note: HowTo structured data lives on /start (public, crawlable).
// /studio requires login so Googlebot cannot index it.

export default async function StudioPage() {
  const sb = await createClient()
  const { data: { user } } = await sb.auth.getUser()
  if (!user) redirect('/auth/login?redirect=/studio')

  return (
    <Suspense>
      <StudioClient />
    </Suspense>
  )
}
