import { redirect } from 'next/navigation'
import { Suspense } from 'react'
import { createClient } from '@/lib/supabase/server'
import { StudioClient } from './StudioClient'
import { SITE_URL } from '@/lib/constants'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title:       'Viral Studio — Generate a Shoot-Ready TikTok Script · TTLike',
  description: 'Paste any TikTok URL. Get a scene-by-scene script, hook breakdown, and pre-shoot checklist in ~20 seconds. Free to try.',
  alternates:  { canonical: `${SITE_URL}/studio` },
  openGraph: {
    title:       'Viral Studio — Shoot-Ready TikTok Scripts · TTLike',
    description: 'From TikTok URL to shoot-ready script in 20 seconds. Hook + body + CTA + checklist — generated by AI.',
    url:         `${SITE_URL}/studio`,
  },
}

const howToSchema = {
  '@context':   'https://schema.org',
  '@type':      'HowTo',
  name:         'How to Generate a Shoot-Ready TikTok Script with TTLike',
  description:  'Turn any viral TikTok product URL into a scene-by-scene script with hook, body lines, CTA, and a pre-shoot checklist — in about 20 seconds.',
  totalTime:    'PT1M',
  tool: [
    { '@type': 'HowToTool', name: 'TTLike Viral Studio', url: `${SITE_URL}/studio` },
    { '@type': 'HowToTool', name: 'TikTok video URL' },
  ],
  supply: [],
  step: [
    {
      '@type':    'HowToStep',
      position:   1,
      name:       'Find a viral TikTok product',
      text:       'Browse TTLike\'s product database or copy the URL of any TikTok video featuring a product you want to film.',
      url:        `${SITE_URL}/studio`,
    },
    {
      '@type':    'HowToStep',
      position:   2,
      name:       'Paste the TikTok URL into Viral Studio',
      text:       'Open TTLike Viral Studio and paste the TikTok video URL. The AI begins analysing the video\'s viral structure immediately.',
      url:        `${SITE_URL}/studio`,
    },
    {
      '@type':    'HowToStep',
      position:   3,
      name:       'Confirm your product details',
      text:       'Enter your product name, category, and key customer pain points. This personalises the generated script for your audience.',
      url:        `${SITE_URL}/studio`,
    },
    {
      '@type':    'HowToStep',
      position:   4,
      name:       'Get your shoot-ready script and checklist',
      text:       'Receive a scene-by-scene script (hook, body, CTA), a hook-pattern breakdown explaining why the original went viral, and a personalised pre-shoot checklist. Copy the script and start filming.',
      url:        `${SITE_URL}/studio`,
    },
  ],
}

export default async function StudioPage() {
  const sb = await createClient()
  const { data: { user } } = await sb.auth.getUser()
  if (!user) redirect('/auth/login?redirect=/studio')

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }}
      />
      <Suspense>
        <StudioClient />
      </Suspense>
    </>
  )
}
